class Buffer:
    width: int
    height: int
    def __init__(self, width: int, height: int) -> None: ...
    def row_text(self, row: int) -> str: ...
    def parse_line(self, row: int, line: str) -> None: ...
    def render_full(self) -> str: ...
    def diff(self, prev: Buffer) -> str: ...

class TextRender:
    visible_w: int
    def __init__(
        self,
        value: object,
        truncation: str | None,
        pl: int,
        pr: int,
        wrap: bool,
    ) -> None: ...
    def __call__(self, w: int, h: int | None = None) -> list[str]: ...

# text
def char_width(ch: str) -> int: ...
def display_width(s: str) -> int: ...
def strip_ansi(s: str) -> str: ...
def slice_at_width(s: str, max_width: int) -> str: ...
def truncate(s: str, max_width: int, *, ellipsis: bool = False) -> str: ...

# layout
def place_at_offsets(items: list[tuple[int, int, str]]) -> str | None: ...
def pad_columns(cells: list[str], col_widths: list[int], spacing: int) -> str: ...
def flex_distribute(
    bases: list[int], grows: list[int], width: int, spacing: int
) -> list[int]: ...
def distribute(total: int, weights: list[int]) -> list[int]: ...
